<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Vitality</title>

    <!-- Bootstrap Core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">

    <!-- Default Fonts (IMPORTANT: Delete these if you are using a different body style!) -->
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,100,200,300,600,500,700,800,900' rel='stylesheet' type='text/css'>

    <!-- Modern Style Fonts (IMPORTANT: Delete these unless you are using body.modern!) -->
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cardo:400,400italic,700' rel='stylesheet' type='text/css'>

    <!-- Vintage Style Fonts (IMPORTANT: Delete these unless you are using body.vintage!) -->
    <link href='https://fonts.googleapis.com/css?family=Sanchez:400italic,400' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cardo:400,400italic,700' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="vendor/owl-carousel/owl.carousel.css" rel="stylesheet" type="text/css">
    <link href="vendor/owl-carousel/owl.theme.css" rel="stylesheet" type="text/css">
    <link href="vendor/owl-carousel/owl.transitions.css" rel="stylesheet" type="text/css">
    <link href="vendor/magnific-popup/magnific-popup.css" rel="stylesheet" type="text/css">
    <link href="vendor/animate.css/animate.min.css" rel="stylesheet" type="text/css">
    <link href="vendor/device-mockups/device-mockups.min.css" rel="stylesheet" type="text/css">

    <!-- Vitality Theme CSS -->
    <!-- INSTRUCTIONS: Uncomment the color scheme you want to use. Red is chosen by default. -->
    <link href="css/vitality-red.css" rel="stylesheet" type="text/css">
    <!-- <link href="css/vitality-aqua.css" rel="stylesheet" type="text/css"> -->
    <!-- <link href="css/vitality-blue.css" rel="stylesheet" type="text/css"> -->
    <!-- <link href="css/vitality-green.css" rel="stylesheet" type="text/css"> -->
    <!-- <link href="css/vitality-orange.css" rel="stylesheet" type="text/css"> -->
    <!-- <link href="css/vitality-pink.css" rel="stylesheet" type="text/css"> -->
    <!-- <link href="css/vitality-purple.css" rel="stylesheet" type="text/css"> -->
    <!-- <link href="css/vitality-tan.css" rel="stylesheet" type="text/css"> -->
    <!-- <link href="css/vitality-turquoise.css" rel="stylesheet" type="text/css"> -->
    <!-- <link href="css/vitality-yellow.css" rel="stylesheet" type="text/css"> -->

    <!-- IE8 support for HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

</head>

<!-- NOTE: Use the .modern or .vintage class to the body element below to see different font pairings! -->

<body id="page-top">

    <!-- Navigation -->
    <!-- Note: navbar-default and navbar-inverse are both supported with this theme. -->
    <nav class="navbar navbar-inverse navbar-fixed-top navbar-expanded">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <i class="fa fa-bars"></i> Menu
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                    John Smith
                </a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a class="page-scroll" href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services">Services</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#process">Process</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#work">Work</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Header -->
    <header style="background-image: url('img/creative/backgrounds/bg-header.jpg');">
        <div class="intro-content">
            <img src="img/creative/profile.svg" class="img-responsive img-centered" alt="">
            <div class="brand-name">John Smith</div>
            <hr class="colored">
            <div class="brand-name-subtext">An Online Portfolio For Creatives</div>
        </div>
        <div class="scroll-down">
            <a class="btn page-scroll" href="#about"><i class="fa fa-angle-down fa-fw"></i></a>
        </div>
    </header>

    <!-- About Section -->
    <section id="about">
        <div class="container wow fadeIn">
            <div class="row">
                <div class="col-md-6">
                    <img src="img/creative/about.jpg" class="img-responsive" alt="">
                </div>
                <div class="col-md-6 text-center">
                    <h1>Hi, I'm John Smith</h1>
                    <hr class="colored">
                    <p>I am a freelance web designer, developer, and photographer based in San Francisco, California. I have a professional background in graphic design, and a degree in Computer Science from the University of Central California.</p>
                    <p>Whether your next project is an online store, website for your business, or a simple brochure, I'll be ready to help!</p>
                </div>
            </div>
        </div>
    </section>

    <!-- Services Section -->
    <section id="services" class="bg-gray">
        <div class="container-fluid">
            <div class="row text-center">
                <div class="col-lg-12 wow fadeIn">
                    <h1>This is what I do</h1>
                    <p>I provide web design, web development, photography, and graphic design services.</p>
                    <hr class="colored">
                </div>
            </div>
            <div class="row text-center content-row">
                <div class="col-md-3 col-sm-6 wow fadeIn" data-wow-delay=".2s">
                    <div class="about-content">
                        <i class="fa fa-laptop fa-4x"></i>
                        <h3>Web Design</h3>
                        <p>This theme includes the retina.js plugin for easy retina image support so your images and graphics will look great on mobile devices!</p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 wow fadeIn" data-wow-delay=".4s">
                    <div class="about-content">
                        <i class="fa fa-code fa-4x"></i>
                        <h3>Web Development</h3>
                        <p>Vitality is built using Bootstrap 3, and is easy to edit and customize. LESS files are included as well for deeper customization.</p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 wow fadeIn" data-wow-delay=".6s">
                    <div class="about-content">
                        <i class="fa fa-camera-retro fa-4x"></i>
                        <h3>Photography</h3>
                        <p>When building this theme, we've paid close attention to how it looks on various screen sizes. Try it out on a phone or tablet!</p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6 wow fadeIn" data-wow-delay=".8s">
                    <div class="about-content">
                        <i class="fa fa-paint-brush fa-4x"></i>
                        <h3>Graphic Design</h3>
                        <p>All of our themes are crafted with care, and we strive to make your experience as one of our customers the best as possible.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Quote Call to Action -->
    <aside class="cta-quote" style="background-image: url('img/creative/backgrounds/bg-aside.jpg');">
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-md-offset-1 wow fadeIn">
                    <span class="quote">Good
                        <span class="text-primary">design</span> is finding that perfect balance between the way something
                    <span class="text-primary">looks</span> and how it
                    <span class="text-primary">functions</span>.</span>
                    <hr class=" colored">
                    <a class="btn btn-outline-light page-scroll" href="#process">Let's Find It</a>
                </div>
            </div>
        </div>
    </aside>

    <!-- Services Section -->
    <section id="process" class="services">
        <div class="container">
            <div class="row text-center">
                <div class="col-lg-12 wow fadeIn">
                    <h2>My Process</h2>
                    <hr class="colored">
                    <p>Here is an overview of how I approach each new project.</p>
                </div>
            </div>
            <div class="row content-row">
                <div class="col-md-4 wow fadeIn" data-wow-delay=".2s">
                    <div class="media">
                        <div class="pull-left">
                            <i class="fa fa-clipboard"></i>
                        </div>
                        <div class="media-body">
                            <h3 class="media-heading">Plan</h3>
                            <ul>
                                <li>Client interview</li>
                                <li>Gather consumer data</li>
                                <li>Create content strategy</li>
                                <li>Analyze research</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 wow fadeIn" data-wow-delay=".4s">
                    <div class="media">
                        <div class="pull-left">
                            <i class="fa fa-pencil"></i>
                        </div>
                        <div class="media-body">
                            <h3 class="media-heading">Create</h3>
                            <ul>
                                <li>Build wireframe</li>
                                <li>Gather client feedback</li>
                                <li>Code development</li>
                                <li>Marketing review</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 wow fadeIn" data-wow-delay=".6s">
                    <div class="media">
                        <div class="pull-left">
                            <i class="fa fa-rocket"></i>
                        </div>
                        <div class="media-body">
                            <h3 class="media-heading">Launch</h3>
                            <ul>
                                <li>Deploy website</li>
                                <li>Market product launch</li>
                                <li>Collect UX data</li>
                                <li>Quarterly maintenence</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Portfolio Carousel Heading -->
    <section id="work" class="bg-gray">
        <div class="container text-center wow fadeIn">
            <h2>Work</h2>
            <hr class="colored">
            <p>Here are some examples of my work.</p>
        </div>
    </section>

    <!-- Portfolio Carousel -->
    <section class="portfolio-carousel wow fadeIn">
        <!-- NOTE: You can add more items to the carousel, or remove items you don't need! -->
        <!-- Carousel Item 1 -->
        <div class="item" style="background-image: url('img/creative/portfolio/carousel/bg-1.jpg')">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-5 col-md-push-7">
                        <div class="project-details">
                            <span class="project-name">Project Name</span>
                            <span class="project-description">Branding, Website Design</span>
                            <hr class="colored">
                            <a href="#portfolioModal1" data-toggle="modal" class="btn btn-outline-light">View Details <i class="fa fa-long-arrow-right fa-fw"></i></a>
                        </div>
                    </div>
                    <div class="col-md-7 col-md-pull-5 hidden-xs">
                        <div class="device-container">
                            <div class="device-mockup macbook portrait black">
                                <div class="device">
                                    <div class="screen">
                                        <img src="img/creative/portfolio/carousel/screen-1a.jpg" class="img-responsive" alt="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Carousel Item 2 -->
        <div class="item" style="background-image: url('img/creative/portfolio/carousel/bg-2.jpg')">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-5 col-md-push-7">
                        <div class="project-details">
                            <span class="project-name">Project Name</span>
                            <span class="project-description">Branding, Website Design</span>
                            <hr class="colored">
                            <a href="#portfolioModal2" data-toggle="modal" class="btn btn-outline-light">View Details <i class="fa fa-long-arrow-right fa-fw"></i></a>
                        </div>
                    </div>
                    <div class="col-md-7 col-md-pull-5 hidden-xs">
                        <div class="device-container">
                            <div class="device-mockup macbook portrait black">
                                <div class="device">
                                    <div class="screen">
                                        <img src="img/creative/portfolio/carousel/screen-2a.jpg" class="img-responsive" alt="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Carousel Item 3 -->
        <div class="item" style="background-image: url('img/creative/portfolio/carousel/bg-3.jpg')">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-5 col-md-push-7">
                        <div class="project-details">
                            <span class="project-name">Project Name</span>
                            <span class="project-description">Branding, Website Design</span>
                            <hr class="colored">
                            <a href="#portfolioModal3" data-toggle="modal" class="btn btn-outline-light">View Details <i class="fa fa-long-arrow-right fa-fw"></i></a>
                        </div>
                    </div>
                    <div class="col-md-7 col-md-pull-5 hidden-xs">
                        <div class="device-container">
                            <div class="device-mockup macbook portrait black">
                                <div class="device">
                                    <div class="screen">
                                        <img src="img/creative/portfolio/carousel/screen-3a.jpg" class="img-responsive" alt="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Carousel Item 4 -->
        <div class="item" style="background-image: url('img/creative/portfolio/carousel/bg-4.jpg')">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-5 col-md-push-7">
                        <div class="project-details">
                            <span class="project-name">Project Name</span>
                            <span class="project-description">Branding, Website Design</span>
                            <hr class="colored">
                            <a href="#portfolioModal4" data-toggle="modal" class="btn btn-outline-light">View Details <i class="fa fa-long-arrow-right fa-fw"></i></a>
                        </div>
                    </div>
                    <div class="col-md-7 col-md-pull-5 hidden-xs">
                        <div class="device-container">
                            <div class="device-mockup macbook portrait black">
                                <div class="device">
                                    <div class="screen">
                                        <img src="img/creative/portfolio/carousel/screen-4.jpg" class="img-responsive" alt="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Portfolio Grid Section -->
    <section>
        <div class="container text-center wow fadeIn">
            <h2>Portfolio</h2>
            <hr class="colored">
            <p>Here are some other projects that I've worked on.</p>
            <div class="row content-row">
                <div class="col-lg-12">
                    <div class="portfolio-filter">
                        <ul id="filters" class="clearfix">
                            <li>
                                <span class="filter active" data-filter="all">All</span>
                            </li>
                            <li>
                                <span class="filter" data-filter=".identity">Identity</span>
                            </li>
                            <li>
                                <span class="filter" data-filter=".graphic">Graphic</span>
                            </li>
                            <li>
                                <span class="filter" data-filter=".web">Web</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div id="portfoliolist">
                        <!-- NOTE: You can add more items to the grid, or remove items you don't need! -->
                        <!-- Grid Item 1 -->
                        <div class="mix identity" href="img/creative/portfolio/grid/grid-1.jpg" title="Client Name">
                            <div class="portfolio-wrapper">
                                <img src="img/creative/portfolio/grid/grid-1.jpg" alt="">
                                <div class="caption">
                                    <div class="caption-text">
                                        <a class="text-title">Client Name</a>
                                        <span class="text-category">Brand Identity</span>
                                    </div>
                                    <div class="caption-bg"></div>
                                </div>
                            </div>
                        </div>
                        <!-- Grid Item 2 -->
                        <div class="mix web" href="img/creative/portfolio/grid/grid-2.jpg" title="Client Name">
                            <div class="portfolio-wrapper">
                                <img src="img/creative/portfolio/grid/grid-2.jpg" alt="">
                                <div class="caption">
                                    <div class="caption-text">
                                        <a class="text-title">Client Name</a>
                                        <span class="text-category">Web Development</span>
                                    </div>
                                    <div class="caption-bg"></div>
                                </div>
                            </div>
                        </div>
                        <!-- Grid Item 3 -->
                        <div class="mix web" href="img/creative/portfolio/grid/grid-3.jpg" title="Client Name">
                            <div class="portfolio-wrapper">
                                <img src="img/creative/portfolio/grid/grid-3.jpg" alt="">
                                <div class="caption">
                                    <div class="caption-text">
                                        <a class="text-title">Client Name</a>
                                        <span class="text-category">Web Development</span>
                                    </div>
                                    <div class="caption-bg"></div>
                                </div>
                            </div>
                        </div>
                        <!-- Grid Item 4 -->
                        <div class="mix identity" href="img/creative/portfolio/grid/grid-4.jpg" title="Client Name">
                            <div class="portfolio-wrapper">
                                <img src="img/creative/portfolio/grid/grid-4.jpg" alt="">
                                <div class="caption">
                                    <div class="caption-text">
                                        <a class="text-title">Client Name</a>
                                        <span class="text-category">Brand Identity</span>
                                    </div>
                                    <div class="caption-bg"></div>
                                </div>
                            </div>
                        </div>
                        <!-- Grid Item 5 -->
                        <div class="mix web" href="img/creative/portfolio/grid/grid-5.jpg" title="Client Name">
                            <div class="portfolio-wrapper">
                                <img src="img/creative/portfolio/grid/grid-5.jpg" alt="">
                                <div class="caption">
                                    <div class="caption-text">
                                        <a class="text-title">Client Name</a>
                                        <span class="text-category">Web Development</span>
                                    </div>
                                    <div class="caption-bg"></div>
                                </div>
                            </div>
                        </div>
                        <!-- Grid Item 6 -->
                        <div class="mix graphic" href="img/creative/portfolio/grid/grid-6.jpg" title="Client Name">
                            <div class="portfolio-wrapper">
                                <img src="img/creative/portfolio/grid/grid-6.jpg" alt="">
                                <div class="caption">
                                    <div class="caption-text">
                                        <a class="text-title">Client Name</a>
                                        <span class="text-category">Graphic Design</span>
                                    </div>
                                    <div class="caption-bg"></div>
                                </div>
                            </div>
                        </div>
                        <!-- Grid Item 7 -->
                        <div class="mix graphic" href="img/creative/portfolio/grid/grid-7.jpg" title="Client Name">
                            <div class="portfolio-wrapper">
                                <img src="img/creative/portfolio/grid/grid-7.jpg" alt="">
                                <div class="caption">
                                    <div class="caption-text">
                                        <a class="text-title">Client Name</a>
                                        <span class="text-category">Graphic Design</span>
                                    </div>
                                    <div class="caption-bg"></div>
                                </div>
                            </div>
                        </div>
                        <!-- Grid Item 8 -->
                        <div class="mix web" href="img/creative/portfolio/grid/grid-8.jpg" title="Client Name">
                            <div class="portfolio-wrapper">
                                <img src="img/creative/portfolio/grid/grid-8.jpg" alt="">
                                <div class="caption">
                                    <div class="caption-text">
                                        <a class="text-title">Client Name</a>
                                        <span class="text-category">Web Development</span>
                                    </div>
                                    <div class="caption-bg"></div>
                                </div>
                            </div>
                        </div>
                        <!-- Grid Item 9 -->
                        <div class="mix identity" href="img/creative/portfolio/grid/grid-9.jpg" title="Client Name">
                            <div class="portfolio-wrapper">
                                <img src="img/creative/portfolio/grid/grid-9.jpg" alt="">
                                <div class="caption">
                                    <div class="caption-text">
                                        <a class="text-title">Client Name</a>
                                        <span class="text-category">Brand Identity</span>
                                    </div>
                                    <div class="caption-bg"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Testomonials Section -->
    <section class="testimonials bg-gray">
        <div class="container wow fadeIn">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1">
                    <div class="testimonials-carousel">
                        <!-- NOTE: You can add more items to the carousel, or remove items you don't need! -->
                        <!-- Testimonial Item 1 -->
                        <div class="item">
                            <div class="row">
                                <div class="col-lg-12">
                                    <p class="lead">"Working with Vitality was both a valuable and rewarding experience."</p>
                                    <hr class="colored">
                                    <p class="quote">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit, temporibus, laborum, dignissimos doloremque corporis alias nostrum recusandae culpa id quisquam harum impedit sed sunt non obcaecati vero ipsam aut fugit?</p>
                                    <div class="testimonial-info">
                                        <div class="testimonial-img">
                                            <img src="img/creative/testimonials/1.jpg" class="img-circle img-responsive" alt="">
                                        </div>
                                        <div class="testimonial-author">
                                            <span class="name">Jim Walker</span>
                                            <p class="small">CEO of Company Name</p>
                                            <div class="stars">
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Testimonial Item 2 -->
                        <div class="item">
                            <div class="row">
                                <div class="col-lg-12">
                                    <p class="lead">"Vitality is a well coded, well documented, and easy to use theme!"</p>
                                    <hr class="colored">
                                    <p class="quote">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem amet rem minus dolorum, facere in soluta explicabo, unde eveniet illo vel, nemo nostrum atque nesciunt facilis quaerat quasi reprehenderit dicta.</p>
                                    <div class="testimonial-info">
                                        <div class="testimonial-img">
                                            <img src="img/creative/testimonials/2.jpg" class="img-circle img-responsive" alt="">
                                        </div>
                                        <div class="testimonial-author">
                                            <span class="name">Ashley Creadle</span>
                                            <p class="small">Creative Director of Company Name</p>
                                            <div class="stars">
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Newsletter Signup Call to Action -->
    <section class="cta-form bg-dark">
        <div class="container text-center">
            <h3>Subscribe to our newsletter!</h3>
            <hr class="colored">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <!-- MailChimp Signup Form -->
                    <div id="mc_embed_signup">
                        <!-- Replace the form action in the line below with your MailChimp embed action! Visit the documentation for additional instructions! -->
                        <form role="form" action="//startbootstrap.us3.list-manage.com/subscribe/post?u=531af730d8629808bd96cf489&amp;id=afb284632f" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" target="_blank" novalidate>
                            <div class="input-group input-group-lg">
                                <input type="email" name="EMAIL" class="form-control" id="mce-EMAIL" placeholder="Email address...">
                                <span class="input-group-btn">
                                    <button type="submit" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary">Subscribe!</button>
                                </span>
                            </div>
                            <div id="mce-responses">
                                <div class="response" id="mce-error-response" style="display:none"></div>
                                <div class="response" id="mce-success-response" style="display:none"></div>
                            </div>
                        </form>
                    </div>
                    <!-- End MailChimp Signup Form -->
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact">
        <div class="container wow fadeIn">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Contact Me</h2>
                    <hr class="colored">
                    <p>I'd love to hear about your next project! Send me a message and I will see if I can help.</p>
                </div>
            </div>
            <div class="row content-row">
                <div class="col-lg-8 col-lg-offset-2">
                    <form name="sentMessage" id="contactForm" novalidate>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Name</label>
                                <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Email Address</label>
                                <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Phone Number</label>
                                <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Message</label>
                                <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <br>
                        <div id="success"></div>
                        <div class="row">
                            <div class="form-group col-xs-12">
                                <button type="submit" class="btn btn-outline-dark">Send</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <!-- Block Button Call to Action -->
    <a href="https://wrapbootstrap.com/theme/vitality-multipurpose-one-page-theme-WB02K3KK3" class="btn btn-block btn-full-width">Buy Vitality Now!</a>

    <!-- Footer -->
    <footer class="footer" style="background-image: url('img/creative/backgrounds/bg-footer.jpg')">
        <div class="container text-center">
            <div class="row">
                <div class="col-md-4 contact-details">
                    <h4><i class="fa fa-phone"></i> Call</h4>
                    <p>555-213-4567</p>
                </div>
                <div class="col-md-4 contact-details">
                    <h4><i class="fa fa-map-marker"></i> Visit</h4>
                    <p>3481 Melrose Place
                        <br>Beverly Hills, CA 90210</p>
                </div>
                <div class="col-md-4 contact-details">
                    <h4><i class="fa fa-envelope"></i> Email</h4>
                    <p><a href="mailto:mail@example.com">mail@example.com</a>
                    </p>
                </div>
            </div>
            <div class="row social">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li><a href="#"><i class="fa fa-facebook fa-fw fa-2x"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-twitter fa-fw fa-2x"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-linkedin fa-fw fa-2x"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row copyright">
                <div class="col-lg-12">
                    <p class="small">&copy; 2016 Start Bootstrap Themes</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- Portfolio Modals -->
    <!-- Example Modal 1: Corresponds with Portfolio Carousel Item 1 -->
    <div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-hidden="true" style="background-image: url('img/creative/portfolio/carousel/bg-1.jpg')">
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl">
                    </div>
                </div>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <h2>Project Name</h2>
                            <hr class="colored">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos modi in tenetur vero voluptatum sapiente dolores eligendi nemo iste ea. Omnis, odio enim sint quam dolorum dolorem. Nostrum, minus, ad.</p>
                        </div>
                        <div class="col-md-8 col-md-offset-2">
                            <div class="device-mockup macbook portrait black">
                                <div class="device">
                                    <div class="screen">

                                        <!-- Modal Mockup Option 1: Single Image (Uncomment Below to Use) -->
                                        <!-- <img src="img/creative/portfolio/carousel/screen-1a.jpg" class="img-responsive" alt=""> -->

                                        <!-- Modal Mockup Option 2: Carousel (Example In Use Below) -->
                                        <div class="mockup-carousel">
                                            <div class="item">
                                                <img src="img/creative/portfolio/carousel/screen-1a.jpg" class="img-responsive" alt="">
                                            </div>
                                            <div class="item">
                                                <img src="img/creative/portfolio/carousel/screen-1b.jpg" class="img-responsive" alt="">
                                            </div>
                                            <div class="item">
                                                <img src="img/creative/portfolio/carousel/screen-1c.jpg" class="img-responsive" alt="">
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-8 col-md-offset-2">
                            <ul class="list-inline item-details">
                                <li>Client: <strong>Start Bootstrap</strong>
                                </li>
                                <li>Date: <strong>April 2015</strong>
                                </li>
                                <li>Service: <strong>Web Development</strong>
                                </li>
                            </ul>
                            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Example Modal 2: Corresponds with Portfolio Carousel Item 2 -->
    <div class="portfolio-modal modal fade" id="portfolioModal2" tabindex="-1" role="dialog" aria-hidden="true" style="background-image: url('img/creative/portfolio/carousel/bg-2.jpg')">
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl">
                    </div>
                </div>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <h2>Project Name</h2>
                            <hr class="colored">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos modi in tenetur vero voluptatum sapiente dolores eligendi nemo iste ea. Omnis, odio enim sint quam dolorum dolorem. Nostrum, minus, ad.</p>
                        </div>
                        <div class="col-md-8 col-md-offset-2">
                            <div class="device-mockup macbook portrait black">
                                <div class="device">
                                    <div class="screen">

                                        <!-- Modal Mockup Option 1: Single Image (Uncomment Below to Use) -->
                                        <!-- <img src="img/creative/portfolio/carousel/screen-2a.jpg" class="img-responsive" alt=""> -->

                                        <!-- Modal Mockup Option 2: Carousel (Example In Use Below) -->
                                        <div class="mockup-carousel">
                                            <div class="item">
                                                <img src="img/creative/portfolio/carousel/screen-2a.jpg" class="img-responsive" alt="">
                                            </div>
                                            <div class="item">
                                                <img src="img/creative/portfolio/carousel/screen-2b.jpg" class="img-responsive" alt="">
                                            </div>
                                            <div class="item">
                                                <img src="img/creative/portfolio/carousel/screen-2c.jpg" class="img-responsive" alt="">
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-8 col-md-offset-2">
                            <ul class="list-inline item-details">
                                <li>Client: <strong>Start Bootstrap</strong>
                                </li>
                                <li>Date: <strong>April 2015</strong>
                                </li>
                                <li>Service: <strong>Web Development</strong>
                                </li>
                            </ul>
                            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Example Modal 3: Corresponds with Portfolio Carousel Item 3 -->
    <div class="portfolio-modal modal fade" id="portfolioModal3" tabindex="-1" role="dialog" aria-hidden="true" style="background-image: url('img/creative/portfolio/carousel/bg-3.jpg')">
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl">
                    </div>
                </div>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <h2>Project Name</h2>
                            <hr class="colored">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos modi in tenetur vero voluptatum sapiente dolores eligendi nemo iste ea. Omnis, odio enim sint quam dolorum dolorem. Nostrum, minus, ad.</p>
                        </div>
                        <div class="col-md-8 col-md-offset-2">
                            <div class="device-mockup macbook portrait black">
                                <div class="device">
                                    <div class="screen">

                                        <!-- Modal Mockup Option 1: Single Image (Uncomment Below to Use) -->
                                        <!-- <img src="img/creative/portfolio/carousel/screen-3a.jpg" class="img-responsive" alt=""> -->

                                        <!-- Modal Mockup Option 2: Carousel (Example In Use Below) -->
                                        <div class="mockup-carousel">
                                            <div class="item">
                                                <img src="img/creative/portfolio/carousel/screen-3a.jpg" class="img-responsive" alt="">
                                            </div>
                                            <div class="item">
                                                <img src="img/creative/portfolio/carousel/screen-3b.jpg" class="img-responsive" alt="">
                                            </div>
                                            <div class="item">
                                                <img src="img/creative/portfolio/carousel/screen-3c.jpg" class="img-responsive" alt="">
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-8 col-md-offset-2">
                            <ul class="list-inline item-details">
                                <li>Client: <strong>Start Bootstrap</strong>
                                </li>
                                <li>Date: <strong>April 2015</strong>
                                </li>
                                <li>Service: <strong>Web Development</strong>
                                </li>
                            </ul>
                            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Example Modal 4: Corresponds with Portfolio Carousel Item 4 -->
    <div class="portfolio-modal modal fade" id="portfolioModal4" tabindex="-1" role="dialog" aria-hidden="true" style="background-image: url('img/creative/portfolio/carousel/bg-4.jpg')">
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl">
                    </div>
                </div>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <h2>Project Name</h2>
                            <hr class="colored">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos modi in tenetur vero voluptatum sapiente dolores eligendi nemo iste ea. Omnis, odio enim sint quam dolorum dolorem. Nostrum, minus, ad.</p>
                        </div>
                        <div class="col-md-8 col-md-offset-2">
                            <div class="device-mockup macbook portrait black">
                                <div class="device">
                                    <div class="screen">

                                        <!-- Modal Mockup Option 1: Single Image (Example In Use Below) -->
                                        <img src="img/creative/portfolio/carousel/screen-4.jpg" class="img-responsive" alt="">

                                        <!-- Modal Mockup Option 2: Carousel (Uncomment Below to Use) -->
                                        <!-- <div class="mockup-carousel">
                                            <div class="item">
                                                <img src="img/creative/portfolio/carousel/screen-1a.jpg" class="img-responsive" alt="">
                                            </div>
                                            <div class="item">
                                                <img src="img/creative/portfolio/carousel/screen-2a.jpg" class="img-responsive" alt="">
                                            </div>
                                            <div class="item">
                                                <img src="img/creative/portfolio/carousel/screen-3a.jpg" class="img-responsive" alt="">
                                            </div>
                                        </div> -->

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-8 col-md-offset-2">
                            <ul class="list-inline item-details">
                                <li>Client: <strong>Start Bootstrap</strong>
                                </li>
                                <li>Date: <strong>April 2015</strong>
                                </li>
                                <li>Service: <strong>Web Development</strong>
                                </li>
                            </ul>
                            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Core Scripts -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Plugin Scripts -->
    <script src="vendor/jquery.easing/jquery.easing.min.js"></script>
    <script src="vendor/owl-carousel/owl.carousel.js"></script>
    <script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
    <script src="vendor/vide/jquery.vide.min.js"></script>
    <script src="vendor/mixitup/jquery.mixitup.js"></script>
    <script src="vendor/wow/wow.min.js"></script>

    <!-- Contact Form Scripts -->
    <script src="js/contact_me.js"></script>
    <script src="js/jqBootstrapValidation.js"></script>

    <!-- Vitality Theme Scripts -->
    <script src="js/vitality.js"></script>

</body>

</html>
